### ISSUE TITLE
script no longer works since the last update for Ipfire to Core 161

### ISSUE THREAD

**Issue by Smookydope** [stanvit/nagios-monit-plugin#9]
Hello.
Unfortunately, your script no longer works since the last update for Ipfire to Core 161. I think it has to do with the fact that Python is only available in version 3.

Greetings
Marcel

**Comment by stanvit** [comment]
Hi Marcel, sorry for the late answer.

I have just ran it through [2to3](https://docs.python.org/3/library/2to3.html) conversion tool and pushed new version to [the separate branch](https://github.com/stanvit/nagios-monit-plugin/tree/python3).

I won't be able to test it until next week. Could you please [download it](https://raw.githubusercontent.com/stanvit/nagios-monit-plugin/python3/check_monit.py) and test in your environment?

**Comment by Smookydope** [comment]
Hi Stanvit,

Unfortunately it does not work.
The following error is issued:

```
/usr/lib/nagios/check_monit_test.py -H localhost -p 2812 -u ******* -P *******
/usr/lib/nagios/check_monit_test.py:104: DeprecationWarning: encodestring() is a deprecated alias since 3.1, use encodebytes()
  headers['Authorization'] = 'Basic ' + (base64.encodestring(opts.username + ':' + opts.password)).strip()
Traceback (most recent call last):
  File "/usr/lib/python3.8/base64.py", line 510, in _input_type_check
    m = memoryview(s)
TypeError: memoryview: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/nagios/check_monit_test.py", line 287, in <module>
    main()
  File "/usr/lib/nagios/check_monit_test.py", line 268, in main
    process_monit_response(get_status())
  File "/usr/lib/nagios/check_monit_test.py", line 104, in get_status
    headers['Authorization'] = 'Basic ' + (base64.encodestring(opts.username + ':' + opts.password)).strip()
  File "/usr/lib/python3.8/base64.py", line 540, in encodestring
    return encodebytes(s)
  File "/usr/lib/python3.8/base64.py", line 527, in encodebytes
    _input_type_check(s)
  File "/usr/lib/python3.8/base64.py", line 513, in _input_type_check
    raise TypeError(msg) from err
TypeError: expected bytes-like object, not str
```

I had already tried the 2to3 tool and couldn't get it. 
I think some manual work will be needed.
But unfortunately that is beyond my knowledge. 

Regards

Marcel

**Comment by stanvit** [comment]
Hi Marcel,

Just pushed another fix to [the same branch](https://github.com/stanvit/nagios-monit-plugin/tree/python3). This time I managed to test it against a single monit and it worked fine.

**Comment by Smookydope** [comment]
Hi Stanvit,

now it works great.
I only have the first line
`#!/usr/bin/env python`
in
`#!/usr/bin/env python3`
changed so that I can call the script as follows 
`/usr/lib/nagios/check_monit.py -H localhost -p 2812 -u admin -P *******`

Regards

Marcel
